name: Build and deploy Python app to Azure Web App - backorder-prediction

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose different OS, but Ubuntu is recommended for Python

    steps:
    # 1. Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Use the Python version you are using

    # 3. Install dependencies from requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Deploy to Azure Web App
    - name: Deploy to Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        app-name: backorder-prediction  # Name of your Azure Web App
        slot-name: production  # You can use different slots if necessary
        publish-profile: "${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}"   # Reference to the GitHub secret
        package: .  # Deploy the entire repository
